theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 后端开发工程师/项目管理/技术支持

# 对你自己的简洁描述
description: 执着的IT人

# 你的美照地址
logo: /assets/images/2028732.jpg

# 你的名字
name: 李林(LiLin)

# 你的联系方式
phone: 13909999998

# 你的邮箱
email: LiLin@unkown.com

# 你目前的住址
address: 中国西藏拉萨

# 你毕业院校
school: 西安电子科技大学

# 你的专业
profession: 计算机及其应用

# 你的学位
degree: 大学本科

# 你获得过的证书或奖励
credential: 项目管理工程师
